(() => {
'use strict';
const cfg=window.DANGELO_CONFIG||{},BASE=String(cfg.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const KEY=String(cfg.SUPABASE_ANON_KEY||'');
let periods=[],assignments=[],role='viewer',current=null;
const crews=['Chad','Nick','Bernie','Chava','Gasper','Pablo','Jon','Remy','Sammy','Vactor','Tony Ha'];
const session=()=>{try{return JSON.parse(localStorage.getItem('dangelo_session')||'null')}catch{return null}};
const headers=(x={})=>({apikey:KEY,Authorization:`Bearer ${session()?.access_token||KEY}`,'Content-Type':'application/json',...x});
async function req(path,o={}){const r=await fetch(BASE+path,{...o,headers:{...headers(),...(o.headers||{})}}),t=await r.text();let b=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw new Error(b?.message||b?.error||b||'Request failed');return b}
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function main(){return document.querySelector('#app main')}
function scheduleEls(){const m=main();if(!m)return[];return [...m.children].filter(el=>!['topbar','appTabs','timeOffPage','restorationPage','onCallPage','privateWorkPage'].some(c=>el.classList.contains(c)))}
function ensure(){const tabs=document.getElementById('appTabs'),m=main();if(!tabs||!m)return false;let b=document.getElementById('tabOnCall');if(!b){b=document.createElement('button');b.id='tabOnCall';b.className='appTab';b.type='button';b.textContent='On Call';const t=document.getElementById('tabTimeOff');t?tabs.insertBefore(b,t):tabs.appendChild(b)}if(!document.getElementById('onCallPage')){const p=document.createElement('section');p.id='onCallPage';p.className='onCallPage timeOffHidden';const t=document.getElementById('timeOffPage');t?t.insertAdjacentElement('beforebegin',p):tabs.insertAdjacentElement('afterend',p)}b.onclick=show;return true}
async function load(){const s=session();if(s?.user?.id){const p=await req(`/rest/v1/profiles?id=eq.${s.user.id}&select=role`);role=p?.[0]?.role||'viewer'}[periods,assignments]=await Promise.all([req('/rest/v1/on_call_periods?select=*&order=start_date.desc'),req('/rest/v1/on_call_assignments?select=*&order=normal_crew,employee_name')]);if(!current&&periods.length)current=periods[0].id;render()}
function show(){document.querySelectorAll('.appTab').forEach(x=>x.classList.toggle('active',x.id==='tabOnCall'));['timeOffPage','restorationPage','privateWorkPage'].forEach(id=>{const p=document.getElementById(id);p?.classList.remove('active');p?.classList.add('timeOffHidden')});scheduleEls().forEach(x=>x.classList.add('timeOffHidden'));const p=document.getElementById('onCallPage');p?.classList.remove('timeOffHidden');p?.classList.add('active');load().catch(e=>p.innerHTML='<div class="ocWrap"><div class="ocError">'+esc(e.message)+'</div></div>')}
function hide(){const p=document.getElementById('onCallPage');p?.classList.remove('active');p?.classList.add('timeOffHidden');document.getElementById('tabOnCall')?.classList.remove('active')}
document.addEventListener('click',e=>{if(['tabSchedule','tabPrivateWork','tabRestoration','tabTimeOff'].includes(e.target?.id))hide()},true);
function fmt(d){if(!d)return'';const [y,m,day]=d.split('-');return Number(m)+'/'+Number(day)+'/'+String(y).slice(-2)}
function injectStyle(){if(document.getElementById('onCallStyles'))return;const s=document.createElement('style');s.id='onCallStyles';s.textContent=`
.ocWrap{padding:24px;max-width:1200px;margin:auto}.ocHead{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.ocHead h2{margin:0 0 4px}.ocHead p,.ocEmpty p{margin:0;color:#64748b}.ocPrimary{background:#231f20;color:#fff;border:0;border-radius:8px;padding:10px 14px;font-weight:800;cursor:pointer}.ocPeriods{display:flex;gap:8px;overflow:auto;margin-bottom:18px;padding-bottom:3px}.ocPeriod{border:1px solid #d6dde5;background:#fff;border-radius:9px;padding:8px 12px;text-align:left;white-space:nowrap;cursor:pointer}.ocPeriod.active{background:#231f20;color:#fff;border-color:#231f20}.ocPeriod strong,.ocPeriod span{display:block}.ocPeriod span{font-size:11px;opacity:.72;margin-top:2px}.ocToolbar{display:flex;justify-content:space-between;align-items:center;margin:12px 0}.ocToolbar h3{margin:0}.ocLegend{font-size:12px;color:#64748b}.ocGroups{display:grid;gap:10px}.ocGroup{background:#fff;border:1px solid #dce2e8;border-radius:10px;overflow:hidden}.ocGroupHead{display:flex;justify-content:space-between;align-items:center;background:#f4f6f8;padding:9px 12px}.ocGroupHead strong{text-transform:uppercase;font-size:12px}.ocAdd{border:0;background:transparent;font-weight:800;cursor:pointer}.ocPerson{display:grid;grid-template-columns:minmax(150px,1fr) 110px 220px;align-items:center;gap:10px;padding:9px 12px;border-top:1px solid #edf0f2}.ocPerson small{color:#64748b}.ocCrewBtns{display:flex;gap:5px}.ocCrewBtns button{width:38px;height:32px;border:1px solid #cbd3db;background:#fff;border-radius:7px;font-weight:800;cursor:pointer}.ocCrewBtns button.sel{background:#231f20;color:#fff;border-color:#231f20}.ocEmpty{padding:38px 20px;text-align:center;background:#fff;border:1px dashed #cbd3db;border-radius:10px}.ocModalBack{position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:10000}.ocModal{background:#fff;border-radius:12px;padding:20px;width:min(430px,calc(100vw - 30px));box-shadow:0 20px 60px #0004}.ocModal h3{margin-top:0}.ocModal label{display:block;font-weight:700;font-size:12px;margin:10px 0}.ocModal input,.ocModal select{display:block;width:100%;box-sizing:border-box;padding:9px;margin-top:4px;border:1px solid #cbd3db;border-radius:7px}.ocActions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.ocActions button{padding:9px 13px;border-radius:7px;border:1px solid #cbd3db;background:#fff;font-weight:700}.ocActions .ocPrimary{background:#231f20;color:#fff;border-color:#231f20}@media(max-width:700px){.ocWrap{padding:14px}.ocHead{align-items:center}.ocPerson{grid-template-columns:1fr auto}.ocPerson small{display:none}.ocCrewBtns{grid-column:2}.ocLegend{display:none}}`;document.head.appendChild(s)}
function render(){injectStyle();const p=document.getElementById('onCallPage');if(!p)return;const per=periods.find(x=>x.id===current);p.innerHTML=`<div class="ocWrap"><div class="ocHead"><div><h2>On Call</h2><p>Weekend and holiday crew assignments.</p></div>${role==='supervisor'?'<button id="ocNew" class="ocPrimary">+ New On Call Period</button>':''}</div><div class="ocPeriods">${periods.map(x=>`<button class="ocPeriod ${x.id===current?'active':''}" data-period="${x.id}"><strong>${esc(x.label)}</strong><span>${fmt(x.start_date)} – ${fmt(x.end_date)}</span></button>`).join('')}</div><div id="ocBody"></div></div>`;p.querySelector('#ocNew')?.addEventListener('click',periodModal);p.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.period);render()});const body=p.querySelector('#ocBody');if(!per){body.innerHTML='<div class="ocEmpty"><h3>No on-call periods yet</h3><p>Create the first weekend or holiday period to start assigning crews.</p></div>';return}const rows=assignments.filter(a=>a.period_id===per.id);body.innerHTML=`<div class="ocToolbar"><h3>${esc(per.label)} · ${fmt(per.start_date)} – ${fmt(per.end_date)}</h3><div class="ocLegend">Click 1, 2, or 3 to assign an on-call crew. Click again to clear.</div></div><div class="ocGroups">${crews.map(c=>groupHtml(c,rows)).join('')}</div>`;body.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>employeeModal(per.id,b.dataset.add));body.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>setCrew(Number(b.dataset.assign),Number(b.dataset.crew)));}
function groupHtml(crew,rows){const people=rows.filter(a=>a.normal_crew===crew);return `<section class="ocGroup"><div class="ocGroupHead"><strong>${esc(crew)} Crew</strong>${role==='supervisor'?`<button class="ocAdd" data-add="${esc(crew)}">+ Add Employee</button>`:''}</div>${people.length?people.map(a=>`<div class="ocPerson"><div><strong>${esc(a.employee_name)}</strong></div><small>${esc(a.role||'')}</small><div class="ocCrewBtns">${[1,2,3].map(n=>`<button data-assign="${a.id}" data-crew="${n}" class="${a.on_call_crew===n?'sel':''}">${n}</button>`).join('')}</div></div>`).join(''):'<div class="ocPerson"><div><small>No employees added yet.</small></div></div>'}</section>`}
function modal(inner){const b=document.createElement('div');b.className='ocModalBack';b.innerHTML='<div class="ocModal">'+inner+'</div>';document.body.appendChild(b);b.onclick=e=>{if(e.target===b)b.remove()};b.querySelector('[data-cancel]')?.addEventListener('click',()=>b.remove());return b}
function periodModal(){const b=modal('<h3>New On Call Period</h3><label>Name<input id="ocLabel" placeholder="Weekend, Thanksgiving, Christmas..."></label><label>Start Date<input id="ocStart" type="date"></label><label>End Date<input id="ocEnd" type="date"></label><div class="ocActions"><button data-cancel>Cancel</button><button id="ocSavePeriod" class="ocPrimary">Create</button></div>');b.querySelector('#ocSavePeriod').onclick=async()=>{const label=b.querySelector('#ocLabel').value.trim(),start=b.querySelector('#ocStart').value,end=b.querySelector('#ocEnd').value;if(!label||!start||!end)return alert('Name, start date, and end date are required.');const made=await req('/rest/v1/on_call_periods',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({label,start_date:start,end_date:end})});current=made[0].id;b.remove();await load()}}
function employeeModal(periodId,crew){const b=modal(`<h3>Add Employee</h3><label>Normal Crew<input value="${esc(crew)}" disabled></label><label>Employee Name<input id="ocEmployee"></label><label>Role<select id="ocRole"><option value="">Select role</option><option>Foreman</option><option>Operator</option><option>Driver</option><option>Laborer</option></select></label><div class="ocActions"><button data-cancel>Cancel</button><button id="ocSaveEmployee" class="ocPrimary">Add</button></div>`);b.querySelector('#ocSaveEmployee').onclick=async()=>{const name=b.querySelector('#ocEmployee').value.trim();if(!name)return;await req('/rest/v1/on_call_assignments',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({period_id:periodId,employee_name:name,normal_crew:crew,role:b.querySelector('#ocRole').value||null})});b.remove();await load()}}
async function setCrew(id,n){if(role!=='supervisor')return;const a=assignments.find(x=>x.id===id);if(!a)return;const val=a.on_call_crew===n?null:n;await req('/rest/v1/on_call_assignments?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({on_call_crew:val})});a.on_call_crew=val;render()}
const obs=new MutationObserver(ensure);obs.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});ensure();
})();