(() => {
  'use strict';
  const cfg=window.DANGELO_CONFIG||{};
  const BASE=String(cfg.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');
  const KEY=String(cfg.SUPABASE_ANON_KEY||'');
  let activeView='schedule', weekStart=mondayOf(new Date()), entries=[], crews=[], role='viewer', enhancing=false;
  let scheduleMarkerTimer=null, scheduleMarkerBusy=false, timeOffPoller=null, timeOffSignature='';
  function session(){try{return JSON.parse(localStorage.getItem('dangelo_session')||'null')}catch{return null}}
  function headers(extra={}){return{apikey:KEY,Authorization:`Bearer ${session()?.access_token||KEY}`,'Content-Type':'application/json',...extra}}
  async function req(path,options={}){const res=await fetch(`${BASE}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const text=await res.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!res.ok)throw new Error(body?.message||body?.error_description||body?.error||body||`Request failed (${res.status})`);return body}
  function mondayOf(d){const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()-((day+6)%7));x.setHours(0,0,0,0);return x}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function iso(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
  function fmt(d){return d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}
  function esc(v){return String(v??'').replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]||ch))}
  function overlaps(e,date){return e.start_date<=date&&e.end_date>=date}
  async function loadRole(){const s=session();if(!s?.user?.id)return;const rows=await req(`/rest/v1/profiles?id=eq.${encodeURIComponent(s.user.id)}&select=role`);role=rows?.[0]?.role||'viewer'}
  async function loadData(){const start=iso(weekStart),end=iso(addDays(weekStart,4));const [offs,crewRows]=await Promise.all([req(`/rest/v1/time_off_entries?select=*&start_date=lte.${end}&end_date=gte.${start}&order=employee_name.asc,start_date.asc`),req('/rest/v1/crews?select=id,name,sort_order&order=sort_order.asc')]);entries=offs||[];crews=crewRows||[];timeOffSignature=JSON.stringify([entries,crews])}
  async function refreshTimeOffIfChanged(){if(activeView!=='timeoff'||document.hidden)return;const start=iso(weekStart),end=iso(addDays(weekStart,4));try{const [offs,crewRows]=await Promise.all([req(`/rest/v1/time_off_entries?select=*&start_date=lte.${end}&end_date=gte.${start}&order=employee_name.asc,start_date.asc`),req('/rest/v1/crews?select=id,name,sort_order&order=sort_order.asc')]);const nextEntries=offs||[],nextCrews=crewRows||[],nextSignature=JSON.stringify([nextEntries,nextCrews]);if(nextSignature!==timeOffSignature){entries=nextEntries;crews=nextCrews;timeOffSignature=nextSignature;renderTimeOff()}}catch{}}
  function startTimeOffPolling(){if(timeOffPoller)return;timeOffPoller=setInterval(()=>{if(document.hidden)return;if(activeView==='schedule')queueScheduleMarkers(true);else refreshTimeOffIfChanged()},3000)}
  function main(){return document.querySelector('#app main')}
  function scheduleEls(){const m=main();if(!m)return[];return Array.from(m.children).filter(el=>!el.classList.contains('topbar')&&!el.classList.contains('appTabs')&&!el.classList.contains('timeOffPage'))}
  function applyView(){const page=document.getElementById('timeOffPage');document.getElementById('tabSchedule')?.classList.toggle('active',activeView==='schedule');document.getElementById('tabTimeOff')?.classList.toggle('active',activeView==='timeoff');scheduleEls().forEach(el=>el.classList.toggle('timeOffHidden',activeView==='timeoff'));page?.classList.toggle('active',activeView==='timeoff');if(activeView==='schedule')queueScheduleMarkers(true)}
  function ensureShell(){const m=main(),top=m?.querySelector('.topbar');if(!m||!top||document.getElementById('appTabs'))return false;const tabs=document.createElement('div');tabs.id='appTabs';tabs.className='appTabs';tabs.innerHTML='<button id="tabSchedule" class="appTab active" type="button">Schedule</button><button id="tabTimeOff" class="appTab" type="button">Time Off</button>';top.insertAdjacentElement('afterend',tabs);const page=document.createElement('section');page.id='timeOffPage';page.className='timeOffPage';tabs.insertAdjacentElement('afterend',page);tabs.querySelector('#tabSchedule').onclick=()=>{activeView='schedule';applyView()};tabs.querySelector('#tabTimeOff').onclick=async()=>{activeView='timeoff';applyView();await refreshTimeOff()};startTimeOffPolling();return true}
  async function refreshTimeOff(){const page=document.getElementById('timeOffPage');if(!page)return;page.innerHTML='<div class="timeOffEmpty">Loading time off…</div>';try{await loadRole();await loadData();renderTimeOff()}catch(e){page.innerHTML=`<div class="timeOffError">${esc(e.message)}</div>`}}
  function employeeNamesForWeek(){return [...new Set(entries.map(e=>String(e.employee_name||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'}))}
  function renderTimeOff(){const page=document.getElementById('timeOffPage');if(!page)return;const days=Array.from({length:5},(_,i)=>addDays(weekStart,i));const cols=`165px repeat(5,minmax(145px,1fr))`;const crewNames=new Map(crews.map(c=>[c.id,c.name]));const names=employeeNamesForWeek();let grid=`<div class="timeOffGrid" style="grid-template-columns:${cols}"><div class="timeOffHead">EMPLOYEE</div>${days.map(d=>`<div class="timeOffHead">${d.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()} ${d.getMonth()+1}/${d.getDate()}</div>`).join('')}`;if(!names.length){grid+=`<div class="timeOffEmpty" style="grid-column:1/-1">No employee time off this week.</div>`}else names.forEach(name=>{grid+=`<div class="timeOffName"><span>${esc(name)}</span></div>`;days.forEach(d=>{const date=iso(d),matches=entries.filter(e=>String(e.employee_name||'').trim().toLowerCase()===name.toLowerCase()&&overlaps(e,date));grid+=`<div class="timeOffCell">${matches.map(e=>`<button type="button" class="timeOffChip" data-entry-id="${e.id}"><strong>OFF</strong>${e.crew_id?`<small>${esc(crewNames.get(e.crew_id)||'Assigned crew')}</small>`:''}${e.note?`<small>${esc(e.note)}</small>`:''}</button>`).join('')}</div>`})});grid+='</div>';page.innerHTML=`<div class="timeOffToolbar"><div class="timeOffNav"><button id="toPrev" type="button">‹</button><strong>${fmt(weekStart)} – ${fmt(addDays(weekStart,4))}, ${addDays(weekStart,4).getFullYear()}</strong><button id="toNext" type="button">›</button></div><div class="timeOffActions"><button id="toToday" type="button">Today</button>${role==='supervisor'?'<button id="addTimeOffBtn" class="primary" type="button">+ Add Time Off</button>':''}</div></div><div class="timeOffWrap">${grid}</div><div class="timeOffHint">Only employees with time off during the selected week appear here. Crew assignment is optional.</div>`;document.getElementById('toPrev').onclick=async()=>{weekStart=addDays(weekStart,-7);await refreshTimeOff()};document.getElementById('toNext').onclick=async()=>{weekStart=addDays(weekStart,7);await refreshTimeOff()};document.getElementById('toToday').onclick=async()=>{weekStart=mondayOf(new Date());await refreshTimeOff()};document.getElementById('addTimeOffBtn')?.addEventListener('click',()=>openEntryModal());document.querySelectorAll('.timeOffChip').forEach(btn=>btn.onclick=()=>openEntryModal(entries.find(e=>e.id===Number(btn.dataset.entryId))))}
  function modal(html){document.getElementById('timeOffModalRoot')?.remove();const wrap=document.createElement('div');wrap.id='timeOffModalRoot';wrap.className='timeOffModalBackdrop';wrap.innerHTML=`<div class="timeOffModal">${html}</div>`;document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};return wrap}
  function openEntryModal(entry=null){if(role!=='supervisor')return;const s=entry?.start_date||iso(weekStart),e=entry?.end_date||s;const wrap=modal(`<h2>${entry?'Edit':'Add'} Time Off</h2><form id="timeOffForm"><label>Employee name<input id="toEmployeeName" type="text" value="${esc(entry?.employee_name||'')}" placeholder="Enter employee name" autocomplete="off" required></label><label>Crew <span class="timeOffOptional">(optional)</span><select id="toCrew"><option value="">Do not show on Schedule</option>${crews.map(c=>`<option value="${c.id}" ${entry?.crew_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Start date<input id="toStart" type="date" value="${s}" required></label><label>End date<input id="toEnd" type="date" value="${e}" required></label><label>Note<textarea id="toNote" rows="3" placeholder="Vacation, doctor, personal, etc.">${esc(entry?.note||'')}</textarea></label><div id="toModalMsg"></div><div class="timeOffModalActions">${entry?'<button id="deleteTimeOff" class="danger" type="button">Delete</button>':''}<button id="cancelTimeOff" type="button">Cancel</button><button class="primary" type="submit">Save</button></div></form>`);setTimeout(()=>wrap.querySelector('#toEmployeeName')?.focus(),0);wrap.querySelector('#cancelTimeOff').onclick=()=>wrap.remove();wrap.querySelector('#deleteTimeOff')?.addEventListener('click',async()=>{if(!confirm('Delete this time off entry?'))return;try{await req(`/rest/v1/time_off_entries?id=eq.${entry.id}`,{method:'DELETE'});wrap.remove();await refreshTimeOff();queueScheduleMarkers(true)}catch(err){wrap.querySelector('#toModalMsg').innerHTML=`<div class="timeOffError">${esc(err.message)}</div>`}});wrap.querySelector('#timeOffForm').onsubmit=async ev=>{ev.preventDefault();const crewValue=wrap.querySelector('#toCrew').value;const employeeName=wrap.querySelector('#toEmployeeName').value.trim();const data={employee_name:employeeName,employee_id:null,crew_id:crewValue?Number(crewValue):null,start_date:wrap.querySelector('#toStart').value,end_date:wrap.querySelector('#toEnd').value,note:wrap.querySelector('#toNote').value.trim()||null};if(!employeeName){wrap.querySelector('#toModalMsg').innerHTML='<div class="timeOffError">Enter an employee name.</div>';return}if(data.end_date<data.start_date){wrap.querySelector('#toModalMsg').innerHTML='<div class="timeOffError">End date cannot be before start date.</div>';return}try{if(entry)await req(`/rest/v1/time_off_entries?id=eq.${entry.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});else await req('/rest/v1/time_off_entries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});wrap.remove();await refreshTimeOff();queueScheduleMarkers(true)}catch(err){wrap.querySelector('#toModalMsg').innerHTML=`<div class="timeOffError">${esc(err.message)}</div>`}}}
  function queueScheduleMarkers(force=false){if(force)document.querySelectorAll('.dropCell').forEach(c=>delete c.dataset.timeOffDecorated);clearTimeout(scheduleMarkerTimer);scheduleMarkerTimer=setTimeout(syncScheduleMarkers,80)}
  async function syncScheduleMarkers(){if(scheduleMarkerBusy)return;const cells=Array.from(document.querySelectorAll('.dropCell[data-crew][data-date]'));if(!cells.length)return;const dates=cells.map(c=>c.dataset.date).sort(),start=dates[0],end=dates[dates.length-1];const key=`${start}|${end}|${cells.length}`;if(cells.every(c=>c.dataset.timeOffDecorated===key))return;scheduleMarkerBusy=true;try{const offs=await req(`/rest/v1/time_off_entries?select=id,employee_name,crew_id,start_date,end_date,note&crew_id=not.is.null&start_date=lte.${end}&end_date=gte.${start}`);cells.forEach(cell=>{cell.querySelectorAll('.scheduleTimeOffMarker').forEach(el=>el.remove());const crewId=Number(cell.dataset.crew),date=cell.dataset.date;(offs||[]).filter(e=>e.crew_id===crewId&&overlaps(e,date)).forEach(e=>{const marker=document.createElement('div');marker.className='scheduleTimeOffMarker';marker.innerHTML=`<strong>${esc(e.employee_name||'Employee')} — OFF</strong>${e.note?`<span>${esc(e.note)}</span>`:''}`;const addButton=cell.querySelector('.addCell');if(addButton)cell.insertBefore(marker,addButton);else cell.appendChild(marker)});cell.dataset.timeOffDecorated=key})}catch{}finally{scheduleMarkerBusy=false}}
  window.DANGELO_TIME_OFF_REFRESH=()=>queueScheduleMarkers(true);
  function enhance(){if(enhancing)return;enhancing=true;try{const added=ensureShell();if(added)applyView();queueScheduleMarkers()}finally{enhancing=false}}
  const obs=new MutationObserver(()=>requestAnimationFrame(enhance));obs.observe(document.getElementById('app'),{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(activeView==='schedule')queueScheduleMarkers(true);else refreshTimeOffIfChanged()}});window.addEventListener('pageshow',()=>{if(activeView==='schedule')queueScheduleMarkers(true);else refreshTimeOffIfChanged()});enhance();
})();